// Code generated by MockGen. DO NOT EDIT.
// Source: message.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockMessageService is a mock of MessageService interface.
type MockMessageService struct {
	ctrl     *gomock.Controller
	recorder *MockMessageServiceMockRecorder
}

// MockMessageServiceMockRecorder is the mock recorder for MockMessageService.
type MockMessageServiceMockRecorder struct {
	mock *MockMessageService
}

// NewMockMessageService creates a new mock instance.
func NewMockMessageService(ctrl *gomock.Controller) *MockMessageService {
	mock := &MockMessageService{ctrl: ctrl}
	mock.recorder = &MockMessageServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessageService) EXPECT() *MockMessageServiceMockRecorder {
	return m.recorder
}

// GetMessageChannel mocks base method.
func (m *MockMessageService) GetMessageChannel() (chan string, chan bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessageChannel")
	ret0, _ := ret[0].(chan string)
	ret1, _ := ret[1].(chan bool)
	return ret0, ret1
}

// GetMessageChannel indicates an expected call of GetMessageChannel.
func (mr *MockMessageServiceMockRecorder) GetMessageChannel() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessageChannel", reflect.TypeOf((*MockMessageService)(nil).GetMessageChannel))
}
